# Generated by Django 3.1.6 on 2021-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210220_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='No Title', max_length=200, unique=True),
        ),
    ]
