# Generated by Django 3.1.6 on 2021-02-17 18:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_field', models.ImageField(upload_to='', verbose_name='uploads/%Y/%m/%d')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
