# Generated by Django 3.1.6 on 2021-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.ImageField(upload_to='images/', verbose_name='uploads/%Y/%m/%d'),
        ),
    ]
