# Generated by Django 3.1.6 on 2021-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210217_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.ImageField(upload_to='images', verbose_name='uploads/%Y/%m/%d'),
        ),
    ]
