# Generated by Django 3.1.6 on 2021-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0002_auto_20210301_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Problem', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='pronoun',
            field=models.CharField(choices=[('undefined', 'undefined'), ('he', 'he'), ('she', 'she')], max_length=20),
        ),
    ]
