# Generated by Django 3.1.6 on 2021-03-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0003_auto_20210301_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'get_latest_by': '-pk', 'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'get_latest_by': ['date'], 'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='body',
            field=models.TextField(default='Write your message here'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact_me.contactcategory'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='johndoh@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='pronoun',
            field=models.CharField(choices=[('undefined', 'undefined'), ('he', 'he'), ('she', 'she')], default='undefined', max_length=20),
        ),
    ]
